## For top_Bob
set _xlnx_shared_i0 [get_pins [list Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync6/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync6/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync6/PRE \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_meta_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_out_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync1_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync2_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync3_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_meta_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync1_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync2_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_rx_inst/rst_in_sync3_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_meta_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_out_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync1_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync2_reg/PRE} \
          {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync3_reg/PRE} \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_meta_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_out_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync1_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync2_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync3_reg/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync6/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync6/PRE \
          Utop_phy/Uphy_wrapper/idelayctrl_reset_gen/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/idelayctrl_reset_gen/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/idelayctrl_reset_gen/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/idelayctrl_reset_gen/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/idelayctrl_reset_gen/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/idelayctrl_reset_gen/reset_sync6/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync6/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync1/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync2/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync3/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync4/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync5/PRE \
          Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync6/PRE]]
set_false_path -to $_xlnx_shared_i0
set_false_path -to $_xlnx_shared_i0
set_false_path -to [get_pins {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync1/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync2/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync3/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync4/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync5/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET/reset_sync6/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync1/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync2/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync3/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync4/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync5/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_ASYNC_RESET_RECCLK/reset_sync6/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync1/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync2/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync3/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync4/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync5/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/gig_ethernet_pcs_pma_0_core/gpcs_pma_inst/MGT_RESET.SYNC_SOFT_RESET_RECCLK/reset_sync6/PRE {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_meta_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_out_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync1_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync2_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_tx_i/U_TXOUTCLK_FREQ_COUNTER/reset_synchronizer_testclk_rst_inst/rst_in_sync3_reg/PRE} Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync6/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync5/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync4/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync3/PRE {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_meta_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_out_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync1_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync2_reg/PRE} {Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_cpll_cal_gtye4.gen_cpll_cal_inst[0].gen_inst_cpll_cal.gtwizard_ultrascale_v1_7_13_gtye4_cpll_cal_inst/reset_synchronizer_resetin_tx_inst/rst_in_sync3_reg/PRE} Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_all_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_any_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_datapath_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_rx_pll_and_datapath_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_any_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_datapath_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_gtwiz_reset_tx_pll_and_datapath_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_meta_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_out_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync1_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync2_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/gig_ethernet_pcs_pma_0_gt_i/inst/gen_gtwizard_gtye4_top.gig_ethernet_pcs_pma_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_reset_controller_internal.gen_single_instance.gtwiz_reset_inst/reset_synchronizer_txprogdivreset_inst/rst_in_sync3_reg/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync1/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync2/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync3/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync4/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync5/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_encommaalign/reset_sync6/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync1/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync2/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync3/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync4/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync5/PRE Utop_phy/Uphy_wrapper/core_wrapper_i/inst/pcs_pma_block_i/transceiver_inst/reclock_rxreset/reset_sync6/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync2/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_wr_reset/reset_sync1/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync6/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync5/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync4/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync3/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync1/PRE Utop_phy/Uphy_wrapper/tx_elastic_buffer_inst/gen_rd_reset/reset_sync2/PRE}]

set_property PACKAGE_PIN K22 [get_ports clk_300M_p]
set_property PACKAGE_PIN K23 [get_ports clk_300M_n]
set_property IOSTANDARD LVDS [get_ports clk_300M_n]
set_property IOSTANDARD LVDS [get_ports clk_300M_p]

#set_property PACKAGE_PIN P6 [get_ports gtrefclk_n_B]
#set_property PACKAGE_PIN P7 [get_ports gtrefclk_p_B]

set_property PACKAGE_PIN M6 [get_ports gtrefclk_n]
set_property PACKAGE_PIN M7 [get_ports gtrefclk_p]

#set_property PACKAGE_PIN U24 [get_ports gtrefclk_n]
#set_property PACKAGE_PIN T24 [get_ports gtrefclk_p]
#set_property IOSTANDARD LVDS [get_ports gtrefclk_n]
#set_property IOSTANDARD LVDS [get_ports gtrefclk_p]

#set_property PACKAGE_PIN F12 [get_ports gtrefclk_n]
#set_property PACKAGE_PIN G12 [get_ports gtrefclk_p]

set_property PACKAGE_PIN K25 [get_ports output_clk]
set_property IOSTANDARD SSTL12 [get_ports output_clk]


set_property PACKAGE_PIN M2 [get_ports rxp]
set_property PACKAGE_PIN M1 [get_ports rxn]
set_property PACKAGE_PIN N5 [get_ports txp]
set_property PACKAGE_PIN N4 [get_ports txn]

set_property PACKAGE_PIN AB14 [get_ports tx_disable]
set_property IOSTANDARD LVCMOS33 [get_ports tx_disable]

#set_property PACKAGE_PIN L5 [get_ports txp_B]
#set_property PACKAGE_PIN L4 [get_ports txn_B]
#set_property PACKAGE_PIN K2 [get_ports rxp_B]
#set_property PACKAGE_PIN K1 [get_ports rxn_B]

#set_property PACKAGE_PIN AA14 [get_ports tx_disable_B]
#set_property IOSTANDARD LVCMOS33 [get_ports tx_disable_B]

#set_property PACKAGE_PIN N24 [get_ports txp]
#set_property PACKAGE_PIN P24 [get_ports txn]
#set_property PACKAGE_PIN U26 [get_ports rxp]
#set_property PACKAGE_PIN V26 [get_ports rxn]





#set_property IOSTANDARD LVCMOS33 [get_ports {sum[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sum[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sum[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sum[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sum[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sum[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sum[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sum[0]}]

#set_property PACKAGE_PIN G10 [get_ports {sum[7]}]
#set_property PACKAGE_PIN G9 [get_ports {sum[6]}]
#set_property PACKAGE_PIN F10 [get_ports {sum[5]}]
#set_property PACKAGE_PIN F9 [get_ports {sum[4]}]
#set_property PACKAGE_PIN E11 [get_ports {sum[3]}]
#set_property PACKAGE_PIN E10 [get_ports {sum[2]}]
#set_property PACKAGE_PIN D9 [get_ports {sum[1]}]
#set_property PACKAGE_PIN C9 [get_ports {sum[0]}]
# SW13.1
set_property PACKAGE_PIN G11 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# SW13.2
set_property PACKAGE_PIN H11 [get_ports independent_clk_en]
# SW13.3
set_property PACKAGE_PIN H9 [get_ports io_refclk_en]
# SW13.4
set_property PACKAGE_PIN J9 [get_ports gmii_rx_clk_en]

set_property IOSTANDARD LVCMOS33 [get_ports independent_clk_en]
set_property IOSTANDARD LVCMOS33 [get_ports io_refclk_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii_rx_clk_en]

set_property PACKAGE_PIN G10 [get_ports {tcp_status[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[7]}]
set_property PACKAGE_PIN G9 [get_ports {tcp_status[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[6]}]
set_property PACKAGE_PIN F10 [get_ports {tcp_status[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[5]}]
set_property PACKAGE_PIN F9 [get_ports {tcp_status[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[4]}]

set_property PACKAGE_PIN E11 [get_ports {tcp_status[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[3]}]
set_property PACKAGE_PIN E10 [get_ports {tcp_status[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[2]}]
set_property PACKAGE_PIN D9 [get_ports {tcp_status[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[1]}]
set_property PACKAGE_PIN C9 [get_ports {tcp_status[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tcp_status[0]}]

set_property PACKAGE_PIN A9 [get_ports start_switch]
set_property IOSTANDARD LVCMOS33 [get_ports start_switch]

set_property PACKAGE_PIN C11 [get_ports start_TX]
set_property IOSTANDARD LVCMOS33 [get_ports start_TX]

#set_property PACKAGE_PIN G10 [get_ports link_status]
#set_property IOSTANDARD LVCMOS33 [get_ports link_status]
#set_property PACKAGE_PIN G9 [get_ports achieve]
#set_property IOSTANDARD LVCMOS33 [get_ports achieve]

#set_property PACKAGE_PIN F10 [get_ports handshake1]
#set_property IOSTANDARD LVCMOS33 [get_ports handshake1]
#set_property PACKAGE_PIN F9 [get_ports handshake]
#set_property IOSTANDARD LVCMOS33 [get_ports handshake]

#set_property PACKAGE_PIN E11 [get_ports handshake0]
#set_property IOSTANDARD LVCMOS33 [get_ports handshake0]
#set_property PACKAGE_PIN E10 [get_ports disconnect]
#set_property IOSTANDARD LVCMOS33 [get_ports disconnect]
#set_property PACKAGE_PIN D9 [get_ports gmii_rx_dv_]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii_rx_dv_]

#connect_debug_port u_ila_1/probe0 [get_nets [list gmii_tx_en]]
#connect_debug_port u_ila_2/probe0 [get_nets [list {dut/gmii_txd_reg[0]} {dut/gmii_txd_reg[1]} {dut/gmii_txd_reg[2]} {dut/gmii_txd_reg[3]} {dut/gmii_txd_reg[4]} {dut/gmii_txd_reg[5]} {dut/gmii_txd_reg[6]} {dut/gmii_txd_reg[7]}]]


## Control Gray Code delay and skew across clock boundary
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/reclock_rd_addrgray*/data_sync*}] -filter {REF_PIN_NAME =~ D}]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/reclock_wr_addrgray*/data_sync*}] -filter {REF_PIN_NAME =~ D}]

## Constrain between Distributed Memory (output data) and the 1st set of flip-flops

set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *reset_sync*}] -filter {REF_PIN_NAME =~ PRE}]





create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Utop_phy/Uphy_wrapper/core_wrapper_i/inst/core_clocking_i/userclk2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {gmii_txd[0]} {gmii_txd[1]} {gmii_txd[2]} {gmii_txd[3]} {gmii_txd[4]} {gmii_txd[5]} {gmii_txd[6]} {gmii_txd[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 40 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {tag_B2A[0]} {tag_B2A[1]} {tag_B2A[2]} {tag_B2A[3]} {tag_B2A[4]} {tag_B2A[5]} {tag_B2A[6]} {tag_B2A[7]} {tag_B2A[8]} {tag_B2A[9]} {tag_B2A[10]} {tag_B2A[11]} {tag_B2A[12]} {tag_B2A[13]} {tag_B2A[14]} {tag_B2A[15]} {tag_B2A[16]} {tag_B2A[17]} {tag_B2A[18]} {tag_B2A[19]} {tag_B2A[20]} {tag_B2A[21]} {tag_B2A[22]} {tag_B2A[23]} {tag_B2A[24]} {tag_B2A[25]} {tag_B2A[26]} {tag_B2A[27]} {tag_B2A[28]} {tag_B2A[29]} {tag_B2A[30]} {tag_B2A[31]} {tag_B2A[32]} {tag_B2A[33]} {tag_B2A[34]} {tag_B2A[35]} {tag_B2A[36]} {tag_B2A[37]} {tag_B2A[38]} {tag_B2A[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[0]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[1]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[2]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[3]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[4]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[5]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[6]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[7]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[8]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[9]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[10]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[11]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[12]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[13]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[14]} {u_Bob/Unetwork_B2A/UframeGen/base_addr_tmp[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list u_Bob/Unetwork_B2A/ack_received]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list gmii_tx_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list gmii_tx_er]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list Utop_phy/Uphy_wrapper/core_wrapper_i/inst/core_clocking_i/rxuserclk2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {gmii_rxd[0]} {gmii_rxd[1]} {gmii_rxd[2]} {gmii_rxd[3]} {gmii_rxd[4]} {gmii_rxd[5]} {gmii_rxd[6]} {gmii_rxd[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 40 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {tag_A2B[0]} {tag_A2B[1]} {tag_A2B[2]} {tag_A2B[3]} {tag_A2B[4]} {tag_A2B[5]} {tag_A2B[6]} {tag_A2B[7]} {tag_A2B[8]} {tag_A2B[9]} {tag_A2B[10]} {tag_A2B[11]} {tag_A2B[12]} {tag_A2B[13]} {tag_A2B[14]} {tag_A2B[15]} {tag_A2B[16]} {tag_A2B[17]} {tag_A2B[18]} {tag_A2B[19]} {tag_A2B[20]} {tag_A2B[21]} {tag_A2B[22]} {tag_A2B[23]} {tag_A2B[24]} {tag_A2B[25]} {tag_A2B[26]} {tag_A2B[27]} {tag_A2B[28]} {tag_A2B[29]} {tag_A2B[30]} {tag_A2B[31]} {tag_A2B[32]} {tag_A2B[33]} {tag_A2B[34]} {tag_A2B[35]} {tag_A2B[36]} {tag_A2B[37]} {tag_A2B[38]} {tag_A2B[39]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list gmii_rx_dv]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list gmii_rx_er]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list Uclk_gen/clk_wiz_0/inst/clk_out1_375M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 4 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX[0]} {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX[1]} {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX[2]} {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 4 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX_next[0]} {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX_next[1]} {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX_next[2]} {u_Bob/Unetwork_B2A/UframeGen/network_fsm_TX_next[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 16 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[0]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[1]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[2]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[3]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[4]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[5]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[6]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[7]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[8]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[9]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[10]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[11]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[12]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[13]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[14]} {u_Bob/Unetwork_B2A/UframeGen/sizeTX_msg_buf[15]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 4 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX_next[0]} {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX_next[1]} {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX_next[2]} {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX_next[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 4 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list {u_Bob/Unetwork_B2A/network_fsm_TCP[0]} {u_Bob/Unetwork_B2A/network_fsm_TCP[1]} {u_Bob/Unetwork_B2A/network_fsm_TCP[2]} {u_Bob/Unetwork_B2A/network_fsm_TCP[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 3 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list {u_Bob/Unetwork_B2A/transfer_fsm[0]} {u_Bob/Unetwork_B2A/transfer_fsm[1]} {u_Bob/Unetwork_B2A/transfer_fsm[2]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 4 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX[0]} {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX[1]} {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX[2]} {u_Bob/Unetwork_B2A/UframeSniffer/network_fsm_RX[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe7]
set_property port_width 1 [get_debug_ports u_ila_2/probe7]
connect_debug_port u_ila_2/probe7 [get_nets [list u_Bob/Unetwork_B2A/received_valid]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe8]
set_property port_width 1 [get_debug_ports u_ila_2/probe8]
connect_debug_port u_ila_2/probe8 [get_nets [list u_Bob/Unetwork_B2A/UframeGen/transfer_complete]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe9]
set_property port_width 1 [get_debug_ports u_ila_2/probe9]
connect_debug_port u_ila_2/probe9 [get_nets [list u_Bob/Unetwork_B2A/UframeGen/transfer_complete_next]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe10]
set_property port_width 1 [get_debug_ports u_ila_2/probe10]
connect_debug_port u_ila_2/probe10 [get_nets [list u_Bob/Unetwork_B2A/transfer_en]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe11]
set_property port_width 1 [get_debug_ports u_ila_2/probe11]
connect_debug_port u_ila_2/probe11 [get_nets [list u_Bob/Unetwork_B2A/transfer_en_next]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_fast]
